#!/bin/bash
# Cross-platform linux update script
# Mon Dec 30 23:14:13 IST 2019
# Author: https://github.com/dhruvildave

readonly dist="$(grep -w "ID" /etc/os-release | cut -d= -f2)"  # Find the name of distro

yellow() { echo -e "\\nUpdating \\033[01;33m$1\\033[00m"; }  # Prints the argument in yellow color

# Base package manager
[[ "$dist" == "fedora" ]] ||
[[ "$dist" == "\"centos\"" ]] &&
    [[ -x "$(command -v dnf)" ]] &&
        yellow "dnf" &&
        sudo dnf upgrade -y ||

[[ "$dist" == "debian" ]] ||
[[ "$dist" == "ubuntu" ]] ||
[[ "$dist" == "kali" ]] &&
    [[ -x "$(command -v apt)" ]] &&
        yellow "apt" &&
        sudo apt update &&
        sudo apt full-upgrade -y &&
        sudo apt autoremove -y ||

[[ "$dist" == "\"opensuse-tumbleweed\"" ]] &&
    proc="$(pgrep -u root packagekitd)" &&
    [[ -x "$proc" ]] &&
        sudo kill "$proc" &&
        unset proc &&

    [[ -x "$(command -v zypper)" ]] &&
        yellow "zypper" &&
        sudo zypper dup -y

# Conda
[[ -x "$(command -v conda)" ]] &&
    yellow "conda->base" &&
    conda update --all -y -n base &&
    [[ -d "$HOME/miniconda3/" ]] &&
        for i in "$HOME/miniconda3/envs"/*; do
            [[ -e "$i" ]] || break  # No user defined envs
            name="$(echo "$i" | rev | cut -d/ -f1 | rev)"
            [[ "$name" == torch ]] && continue  # Do not update torch

            yellow "conda->$name"
            conda update --all -y -n "$name"
        done
    unset name

# Flatpak
yellow "flatpak"
[[ -x "$(command -v flatpak)" ]] &&
    sudo flatpak update -y

# NodeJS
[[ -x "$(command -v node | grep -w nvm)" ]] &&
    yellow "NodeJS" &&
    ver="$(node --version)" &&
    . "$NVM_DIR/nvm.sh" &&
    nvm install --lts &&
    [[ "$(node --version)" != "$ver" ]] &&
        nvm uninstall "$ver" &&
        nvm use node &&
    unset ver

unset -f yellow
